AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: EC2 stop
Resources:
  RedshiftEC2Stop:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: EC2 stop
      MemorySize: 128
      Timeout: 180
      Role: '+++++++'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 ? * MON-FRI *)
        Schedule2:
          Type: Schedule
          Properties:
            Schedule: cron(0 5 ? * SAT-SUN *)
      Environment:
        Variables:
          CUSTOM_LOG_GROUP: +++++++
          CUSTOM_LOG_STREAM: +++++++
          INSTANCE_ID: +++++++
          SUBJECT: EC2 stop failed
          TOPIC_ARN: '+++++++'
